rad = float(input("Enter the radius of the circle : "))
print("The area of the circle with radius",rad,"is: ", ((22/7)*rad*rad))
filen = input("Input the Filename: ")
f= filen.split(".")
print ("The extension of the file is : "+ f[-1])